<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MoodleApi\Module'                        => __DIR__ . '/Module.php',
    'MoodleApi\Controller\CourseController' => __DIR__ . '/src/MoodleApi/Controller/CourseController.php',
    'MoodleApiTest\Framework\TestCase'        => __DIR__ . '/tests/MoodleApi/Framework/TestCase.php',
    'MoodleApiTest\SampleTest'                => __DIR__ . '/tests/MoodleApi/SampleTest.php',
);
